<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Clientes extends Model
{
    protected $table = 'cli';
    protected $primaryKey = 'cli_codigo';
    public $incrementing = false;
    protected $keyType = 'string';

    protected $fillable = [
        'cli_razonsocial',
        'cli_fantasia',
        'cli_direccion',
        'cli_localidad',
        'cli_codigopostal',
        'cli_preftel',
        'cli_telefono',
        'cli_telefono1',
        'cli_telefono2',
        'cli_telefono3',
        'cli_telefono4',
        'cli_telefono5',
        'cli_telefono6',
        'cli_telefono7',
        'cli_telefono8',
        'cli_telefono9',
        'cli_telefono10',
        'cli_telefono11',
        'cli_telpago1',
        'cli_telpago2',
        'cli_telpago3',
        'cli_telpago4',
        'cli_horario1',
        'cli_horario2',
        'cli_fax',
        'cli_codigopais',
        'cli_codigoprv',
        'cli_debito',
        'cli_email',
        'cli_email2',
        'cli_email3',
        'cli_webpage',
        'cli_cuit',
        'cli_codigociva',
        'cli_codigopag',
        'cli_estado',
        'cli_codigolp',
        'cli_nroprecio',
        'cli_fechaalta',
        'cli_generico',
        'cli_codigotcli',
        'cli_formcuit',
        'cli_importecredito',
        'cli_descuentoglobal',
        'cli_descuento1',
        'cli_descuento2',
        'cli_descuento3',
        'cli_descuento4',
        'cli_contacto',
        'cli_contacto1',
        'cli_contacto2',
        'cli_contacto3',
        'cli_promotor',
        'cli_codigozon',
        'cli_contactopago',
        'cli_vctomax',
        'cli_vctomax1',
        'cli_factura',
        'cli_usuario',
        'cli_ultfot',
        'cli_ultot',
        'cli_mailing',
        'cli_diapgo',
        'cli_diarec',
        'cli_lapsomax',
        'cli_montomax',
        'cli_factmax',
        'cli_autoriza',
        'cli_causa',
        'cli_codalt',
        'cli_interno',
        'cli_externo',
        'cli_calidad',
        'cli_muestras',
        'cli_informe',
        'cli_facturar',
        'cli_gestion',
        'cli_periodicidad',
        'cli_obs',
        'cli_obs1',
        'cli_obscoti',
        'cli_zonacom',
        'cli_carpeta',
        'cli_codigotrans',
        'cli_codigoven',
        'cli_fechaultcompra',
        'cli_codigorepar',
        'cli_observaciones',
        'cli_codigocomi',
        'cli_codigocrub',
        'cli_codigocanal',
        'cli_obsgeneral',
        'cli_idcontacto',
        'cli_fleteabona',
        'cli_tipoiibb',
        'cli_numeroiibb',
    ];
}